spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3306/test-db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
